package org.usfirst.frc.team3166.robot.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc.team3166.robot.*;

/**
*
*/
public class TankDrive extends Command {

 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

 // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
 public TankDrive() {
 	requires(Robot.kDriveTrain);
 }

 // Called just before this Command runs the first time
 protected void initialize() {
 	
 }

 // Called repeatedly when this Command is scheduled to run
 protected void execute() {
 	Robot.kDriveTrain.drive(Robot.m_oi.getDriver());
 }

 // Make this return true when this Command no longer needs to run execute()
 protected boolean isFinished() {
     return false;
 }

 // Called once after isFinished returns true
 protected void end() {
 	Robot.kDriveTrain.drive(0,0);
 }

 // Called when another command which requires one or more of the same
 // subsystems is scheduled to run
 protected void interrupted() {
 	end();
 }
}
