// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3245.CompCode3245.commands;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.interfaces.Gyro;

import org.usfirst.frc3245.CompCode3245.Robot;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;
import org.usfirst.frc3245.CompCode3245.RobotMap;
import edu.wpi.first.wpilibj.Timer;


/**
 *
 */
@SuppressWarnings("deprecation")
public class DriveStr8 extends Command {
	
	private static final double Kp = 0;
	RobotDrive myDrive;
	TalonSRX frontLeft, rearLeft, frontRight, rearRight;
	private RobotDrive myRobot;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveStr8() {
    	
    	double Kp = 0.03;
    	
    	AnalogGyro gyro = new AnalogGyro(1);
    	RobotDrive myRobot = new RobotDrive(1,2); //CHANGE bc this is for Jauguars
    	myRobot.setExpiration(0.10);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	
    		AnalogGyro gyro = null; //Don't know what this means
			gyro.reset();

	while (isAutonomous()) {
		
		double angle = gyro.getAngle(); //get current heading
	
		
		RobotDrive myRobot = null; 
		myRobot.drive(-1.0, -angle*Kp);//drive towards heading 0
		
		Timer.delay(0.004);
		
	}
    	
    	myRobot.drive(0.0, 0.0);
    	

    }
 private boolean isAutonomous() {
		// TODO Auto-generated method stub
		return false;
	}

// Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.driveTrain.drive(Robot.oi.getDriver());
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	
    	
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
